/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author sirna
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblTotalMaterials = new javax.swing.JLabel();
        lblTotalSuppliers = new javax.swing.JLabel();
        lblTotalCleaners = new javax.swing.JLabel();
        lblLowStock = new javax.swing.JLabel();
        btnMaterials = new javax.swing.JButton();
        btnSuppliers = new javax.swing.JButton();
        btnCleaners = new javax.swing.JButton();
        btnIssueStock = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jLabel1.setText("Cleaning inventory System");

        lblWelcome.setText("Welcome");

        lblTotalMaterials.setText("Total Materials: 0 ");

        lblTotalSuppliers.setText("Total Suppliers: 0 ");

        lblTotalCleaners.setText("Total Cleaners: 0 ");

        lblLowStock.setText("Low Stock Items: 0");

        btnMaterials.setText("Materials");

        btnSuppliers.setText("Suppliers");

        btnCleaners.setText("Cleaners");

        btnIssueStock.setText("Low Items");

        btnReports.setText("Reports");

        btnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblWelcome))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblTotalSuppliers)
                                .addComponent(lblTotalMaterials)
                                .addComponent(lblTotalCleaners)
                                .addComponent(lblLowStock))
                            .addComponent(btnReports))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogout)
                            .addComponent(btnMaterials)
                            .addComponent(btnSuppliers)
                            .addComponent(btnCleaners)
                            .addComponent(btnIssueStock))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblWelcome)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalMaterials)
                    .addComponent(btnMaterials))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalSuppliers)
                    .addComponent(btnSuppliers))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCleaners)
                    .addComponent(btnCleaners))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLowStock)
                    .addComponent(btnIssueStock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReports)
                    .addComponent(btnLogout))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleaners;
    private javax.swing.JButton btnIssueStock;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaterials;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSuppliers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLowStock;
    private javax.swing.JLabel lblTotalCleaners;
    private javax.swing.JLabel lblTotalMaterials;
    private javax.swing.JLabel lblTotalSuppliers;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
